[workspace]
members = [".", "storekey-derive"]

[workspace.package]
edition = "2024"
version = "0.10.0"
authors = [
	"Tobie Morgan Hitchcock <tobie@surrealdb.com>",
	"Michal Hornicky <mhornick@redhat.com>",
	"Dan Burkert <dan@danburkert.com>",
]
description = "Lexicographic sort-order preserving binary encoding format for key-value stores"
repository = "https://github.com/surrealdb/storekey"
homepage = "https://github.com/surrealdb/storekey"
keywords = ["database", "encoding", "key-value", "kv-store", "serialization"]
categories = ["encoding"]
license = "Apache-2.0"

[package]
name = "storekey"
publish = true
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[workspace.lints]

[features]
default = ["derive"]
derive = ["storekey-derive"]
uuid = ["dep:uuid"]
bytes = ["dep:bytes"]

[dependencies]
storekey-derive = { version = "0.10.0", path = "storekey-derive", optional = true }
uuid = { version = "1.18", optional = true }
bytes = { version = "1.0", optional = true }

