[package]
name = "storekey-derive"
publish = true
edition.workspace = true
version.workspace = true
description = "Private implementation of procedural macros for storekey"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["extra-traits"] }
quote = { version = "1" }
proc-macro2 = "1"

[lints]
workspace = true