name: Publish to crates.io

on:
  push:
    tags:
      - 'v*'

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish crates
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Publish to crates.io
        run: cargo release publish --execute --no-confirm --workspace
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

